### ISSUE TITLE
Last restaurant (Casa Enrique) missing photograph property

### ISSUE THREAD

**Issue by sharynneazhar** [udacity/mws-restaurant-stage-2#4]
Update this:
```
{
    "name": "Casa Enrique",
    "neighborhood": "Queens",
    "address": "5-48 49th Ave, Queens, NY 11101",
    ....
},
```

to: 
```
{
    "name": "Casa Enrique",
    "neighborhood": "Queens",
    "address": "5-48 49th Ave, Queens, NY 11101",
    "photograph": "10",
    ....
},
```

**Comment by sd5869** [comment]
Yes Even I feel this is some issue.

**Comment by alexanderluna** [comment]
I was about to open a new pull request but it seems you already spotted this.

**Comment by avilde** [comment]
Most probably it's missing on purpose and you have to implement a way to show default image if no photograph property exists for a restaurant.

**Comment by krzysiekpiasecki** [comment]
@avilde IMHO - Missing property, when you expect property, is a signal for an error. You can handle for example runtime errors like network error, but you shouldn't hide logic error.

**Comment by alexanderluna** [comment]
@krzysiekpiasecki Never expect to get all the properties 100% of the time. Thats why we do error handling. In real life, there many more things missing when you work with APIs.

**Comment by krzysiekpiasecki** [comment]
@Mycroft1891 In this way you should consequently check all properties of the response. Missing property is a JSON schema error, so it's a logic exception, which should always lead to fix in a source code.

**Comment by avilde** [comment]
Hello, Krzysztof!

I do agree that it should be fixed in source code in a real project which unfortunately might not happen do to lot of bureaucracy on the partner side who created integration.

In frontend you have the option to handle some server side errors but in this restaurant project the rule is: not change server side (stage-3 repo code).

**Comment by Abdulkadir98** [comment]
Hello, so what is the consensus? Do I handle the error to display some other image or I add the property in the forked version?

**Comment by krzysiekpiasecki** [comment]
@Abdulkadir98 At the end I implemented an error handler and fallback image.

**Comment by Abdulkadir98** [comment]
@krzysiekpiasecki Alright, thanks!

**Comment by Iulius90** [comment]
Probably missing on purpose.
I just used the ternary operator to show a "not found" image placeholder instead.


`image.src = restaurant.photograph ? DBHelper.imageUrlForRestaurant(restaurant) : 'img/image_not_found.png'; `

**Comment by sharynneazhar** [comment]
I think the consensus here is that the property is missing for learning purposes. Otherwise, this is an issue for the dev team. If that is the case, +1 to close this issue?

**Comment by gpalsingh** [comment]
Just ran into this problem yesterday. As a quick fix, I instead used the "id" property since it has the same info as "photograph" for this data.
